import { useCallback, useEffect, useState } from 'react';
import Head from 'next/head';
import Header from '../../components/Header';
import PostForm from '../../components/PostForm';
import Loading from '../../components/Loading';
import { createPost, deletePost, fetchPosts, updatePost } from '../../lib/api';
import type { Post, PostInput } from '../../lib/types';

export default function AdminPage(): JSX.Element {
  const [posts, setPosts] = useState<Post[]>([]); const [editing, setEditing] = useState<Post | null>(null); const [loading, setLoading] = useState<boolean>(true); const [notice, setNotice] = useState<string>(''); const [error, setError] = useState<string>('');
  const load = useCallback(async () => { setLoading(true); try { setPosts(await fetchPosts()); } catch { setError('Unable to load posts. Check that the API is running at localhost:8000.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const save = async (input: PostInput): Promise<void> => { try { if (editing) { await updatePost(editing.id, input); setNotice('Post updated successfully.'); } else { await createPost(input); setNotice('Post created successfully.'); } setEditing(null); await load(); } catch { setError('The post could not be saved. Please try again.'); } };
  const remove = async (post: Post): Promise<void> => { if (!window.confirm(`Delete “${post.title}”? This cannot be undone.`)) return; try { await deletePost(post.id); setNotice('Post deleted.'); await load(); } catch { setError('The post could not be deleted.'); } };
  return <><Head><title>Post management — Northstar</title></Head><Header /><main className="container admin"><div className="admin-heading"><div><span className="eyebrow">Workspace</span><h1>Post management</h1></div><button className="button button-dark" onClick={() => setEditing(null)}>＋ New post</button></div>{notice && <div className="notice success" role="status">{notice}<button onClick={() => setNotice('')} aria-label="Dismiss notification">×</button></div>}{error && <div className="notice error" role="alert">{error}<button onClick={() => setError('')} aria-label="Dismiss notification">×</button></div>}<div className="admin-layout"><section className="panel"><h2>{editing ? 'Edit post' : 'Create a post'}</h2><PostForm key={editing?.id || 'new'} initialPost={editing} onSubmit={save} onCancel={() => setEditing(null)} /></section><section className="panel"><h2>All posts <span className="count">{posts.length}</span></h2>{loading ? <Loading label="Loading posts" compact /> : posts.length === 0 ? <div className="empty"><p>No posts yet.</p><button className="text-link" onClick={() => setEditing(null)}>Create your first post</button></div> : <div className="admin-list">{posts.map((post) => <div className="admin-row" key={post.id}><div><strong>{post.title}</strong><small>{post.category || 'Uncategorized'} · {post.published ? 'Published' : 'Draft'}</small></div><div className="row-actions"><button onClick={() => setEditing(post)} aria-label={`Edit ${post.title}`}>Edit</button><button className="danger-text" onClick={() => void remove(post)} aria-label={`Delete ${post.title}`}>Delete</button></div></div>)}</div>}</section></div></main></>;
}
