import { useState } from 'react';
import Layout from '../components/Layout';
import ProtectedRoute from '../components/ProtectedRoute';
import StatusBadge from '../components/StatusBadge';
import Modal from '../components/Modal';

const records = [{ id: 'V-2048', name: 'Arjun Shah', company: 'Miro Labs', host: 'Priya Nair', location: 'Jayanagar', date: 'Today, 11:30 AM' }, { id: 'V-2047', name: 'Sara Thomas', company: 'Northstar', host: 'Rahul Mehta', location: 'WTC', date: 'Today, 02:00 PM' }, { id: 'V-2043', name: 'Dev Malhotra', company: 'CloudNine', host: 'Anita Rao', location: 'Noida', date: 'Tomorrow, 09:00 AM' }];

export default function Approvals() { const [items, setItems] = useState(records); const [rejecting, setRejecting] = useState<string | null>(null); const [reason, setReason] = useState(''); function approve(id: string) { setItems(items.filter((item) => item.id !== id)); } return <ProtectedRoute><Layout title="Approvals" subtitle="Review and manage visitor access requests."><div className="toolbar"><div className="tabs"><button className="tab active">Pending <b>8</b></button><button className="tab">Approved</button><button className="tab">Rejected</button></div><select aria-label="Filter location"><option>All locations</option><option>WTC</option><option>Jayanagar</option><option>Noida</option></select></div><section className="panel"><div className="table-wrap"><table><thead><tr><th>Visitor</th><th>Host</th><th>Location</th><th>Visit date</th><th>Status</th><th>Actions</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.id} · {item.company}</small></td><td>{item.host}</td><td>{item.location}</td><td>{item.date}</td><td><StatusBadge status="PENDING" /></td><td><div className="row-actions"><button className="button mini primary" onClick={() => approve(item.id)}>Approve</button><button className="button mini danger" onClick={() => setRejecting(item.id)}>Reject</button></div></td></tr>)}</tbody></table>{!items.length && <div className="empty-state"><span>✓</span><h3>All caught up</h3><p>No pending visitor requests require your attention.</p></div>}</div></section><Modal open={Boolean(rejecting)} title="Reject visitor request" onClose={() => setRejecting(null)}><p className="muted">Add a reason so the requester can edit and resubmit.</p><textarea value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Reason for rejection" rows={4} /><div className="modal-actions"><button className="button secondary" onClick={() => setRejecting(null)}>Cancel</button><button className="button danger" onClick={() => { setRejecting(null); setReason(''); }}>Reject request</button></div></Modal></Layout></ProtectedRoute>; }
